# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP app to Azure Web App - learningapp007

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read 

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x' # Change to 8.0.x if you are still on .NET 8

      # 1. This compiles the app and puts the DLLs in a folder called 'release'
      - name: Publish with dotnet
        run: dotnet publish -c Release -o ./release

      # 2. This grabs ONLY the compiled 'release' folder
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: ASP-app
          path: ./release 

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write 
      contents: read 

    steps:
      # 3. This downloads the 'release' folder to the deployment runner
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ASP-app
          path: ./release
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1F944B52EA0E4E38A3416F695001C716 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_23A6ED6BAE614D19A3577B7CF10F6DB8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E101CCB36E5A425FBA87CF9A3E6BDF4B }}

      # 4. This deploys ONLY the contents of the 'release' folder to wwwroot
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'learningapp007'
          slot-name: 'Production'
          package: ./release
